services:
  app-server:
    image: ghcr.io/contour-gara/gara-photo-app-server:1.1.20240921152434
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - gara-photo-nw
    healthcheck:
      test: "curl -f http://localhost:8080/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ./photo:/opt/photo
    environment:
      SPRING_PROFILES_ACTIVE: prd
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gara_photo
      SPRING_DATASOURCE_USERNAME: gara
      SPRING_DATASOURCE_PASSWORD: ${GARA_PHOTO_DB_PASSWORD}
      APPLICATION_REPOSITORY: jdbc-client
      TWITTER_OAUTH1_ACCESS_TOKEN: ${GARA_PHOTO_OAUTH1_ACCESS_TOKEN:-oauth1-access-token-dummy}
      TWITTER_OAUTH1_ACCESS_TOKEN_SECRET: ${GARA_PHOTO_OAUTH1_ACCESS_TOKEN_SECRET:-oauth1-access-token-secret-dummy}
      TWITTER_API_KEY: ${GARA_PHOTO_API_KEY:-api-key-dummy}
      TWITTER_API_KEY_SECRET: ${GARA_PHOTO_API_KEY_SECRET:-api-key-secret-dummy}
      TWITTER_CLIENT_ID: ${GARA_PHOTO_CLIENT_ID:-client-id-dummy}
      TWITTER_CLIENT_SECRET: ${GARA_PHOTO_CLIENT_SECRET:-client-secret-dummy}
      TWITTER_REDIRECT_URI: ${GARA_PHOTO_REDIRECT_URI:-http://localhost/dummy}
      TZ: Asia/Tokyo

  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: gara
      POSTGRES_PASSWORD: ${GARA_PHOTO_DB_PASSWORD}
      POSTGRES_DB: gara_photo
      TZ: "Asia/Tokyo"
    networks:
      - gara-photo-nw
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  gara-photo-nw:
    driver: bridge
